---

- hosts: all
  become: yes
  gather_facts: false
  pre_tasks:
    - name: Install python for ansible
      raw: test -e /usr/bin/python || (apt-get update && apt install -y python-minimal)
  roles:
    - spark

