---

- name: Check if java installed
  stat: path={{ java.path }}/{{ java.version }}/bin/java
  register: java_installation

- name: Download JDK from Oracle
  command: "wget --header 'Cookie:oraclelicense=accept-securebackup-cookie' {{ java.download_url}}"
  args:
    creates: "{{ java.archive_name }}"
  when: java_installation.stat.exists == False

- name: Create JDK installation directory
  file: path={{ java.path }} state=directory mode=0755

- name: Extract JDK
  command: "tar xzf {{ java.archive_name }} -C {{ java.path }}"
  args:
    creates: "{{ java.path }}/{{ java.version }}/bin/java"

- name: Set JAVA_HOME
  lineinfile: dest=/etc/profile line="JAVA_HOME={{ java.path }}/{{ java.version }}" state=present

- name: Set alternatives for Java
  alternatives: name=java path={{ java.path }}/{{ java.version }}/bin/java link=/usr/bin/java

- name: Delete archive
  file: path={{ java.archive_name }} state=absent